### ISSUE TITLE
Current push implementation is blocking

### ISSUE THREAD

**Issue by juliushaertl** [daita/stratos#1]
The current push implementation with while/sleep is blocking requests, which means that one webserver worker is always blocked per open browser window: 

https://github.com/daita/stratos/blob/master/lib/Service/PushService.php#L128-L142

I guess we should consider adding the ability to integrate with something like an external websocket based backend or maybe switch to a polling based mechanism by default.

**Comment by daita** [comment]
it seems that https://php.net/session_write_close is [fixing this](https://stackoverflow.com/questions/12401358/why-should-session-write-close-be-used-in-long-polling)

Do you have an actual environment to test this ?

**Comment by daita** [comment]
short polling by default, changeable by setting.

**Comment by juliushaertl** [comment]
You rock :clap:
